version: '3.0'

services:
    node:
        build: ./node
        volumes:
            - ./node/workspace:/root/workspace
            - /root/workspace/node_modules
        tty: true
        container_name: node-alpine