version: '3.0'

services:
    node:
        build: ./node
        ports:
            - 8000:80
        volumes:
            - ./node/workspace:/root/workspace
            - /root/workspace/node_modules
        environment:
            - API_KEY=${API_KEY}
        tty: true
        container_name: node-alpine